# Default Settings
title: YulRun.Dev
description: Under Construction

# External Plugins & Themes
plugins:
  - jekyll-default-layout
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs

