# Default Settings
title: YulRun.Dev
description: Under Construction
logo: "/assets/images/yulrun_logo_trans.png"

# External Plugins & Themes
plugins:
  - jekyll-default-layout
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs

